AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to delete all data from Datalake buckets
  (qs-1nlkhq1oe)
Resources:
  EmptyBuckets:
    Condition: CreateDemoResources
    Properties:
      CuratedDatasets: !Ref 'CuratedBucketName'
      PublishedData: !Ref 'PublishedBucketName'
      ServiceToken: !GetAtt 'EmptyBucketsFunction.Arn'
      SubmissionsBucket: !Ref 'SubmissionsBucketName'
    Type: AWS::CloudFormation::CustomResource
  EmptyBucketsFunction:
    Condition: CreateDemoResources
    Properties:
      Code:
        ZipFile: !Join
          - "\n"
          - - import json
            - import cfnresponse
            - import boto3
            - from botocore.exceptions import ClientError
            - ''
            - s3 = boto3.resource('s3')
            - ''
            - 'def handler(event, context):'
            - '    submissions_bucket = s3.Bucket(event[''ResourceProperties''][''SubmissionsBucket''])'
            - '    curated_datasets = s3.Bucket(event[''ResourceProperties''][''CuratedDatasets''])'
            - '    published_data = s3.Bucket(event[''ResourceProperties''][''PublishedData''])'
            - '    if event[''RequestType''] == ''Delete'':'
            - '        try:'
            - '            submissions_bucket.objects.all().delete()'
            - '            curated_datasets.objects.all().delete()'
            - '            published_data.objects.all().delete()'
            - '            return cfnresponse.send(event, context, cfnresponse.SUCCESS,
              {})'
            - '        except ClientError as e:'
            - '            print(e)'
            - '            return cfnresponse.send(event, context, cfnresponse.FAILED,
              {})'
            - '    else:'
            - '        return cfnresponse.send(event, context, cfnresponse.SUCCESS,
              {})'
      Handler: index.handler
      Role: !Ref 'EmptyBucketsRoleARN'
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Lambda::Function
Conditions:
  CreateDemoResources: !Equals
    - !Ref 'CreateDemonstration'
    - 'yes'
Parameters:
  CreateDemonstration:
    AllowedValues:
      - 'yes'
      - 'no'
    Default: 'no'
    Description: "Set this parameter to no if you don\u2019t want the Quick Start\
      \ to deploy the data lake wizard and load sample data into the Amazon Redshift\
      \ cluster and Kinesis streams. For more information about the wizard, see step\
      \ 4. The following five parameters are used only if Create Demonstration is\
      \ set to yes."
    Type: String
  EmptyBucketsRoleARN:
    Description: EmptyBucketsRole ARN
    Type: String
  CuratedBucketName:
    Description: Bucket name for curated datasets
    Type: String
  PublishedBucketName:
    Description: PublishedData bucket name
    Type: String
  SubmissionsBucketName:
    Description: SubmissionsBucket bucket name
    Type: String
