AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation templates to create AWS Kinesis Firehose endpoints.
  (qs-1nlkhq1oo)
Parameters:
  ElasticsearchAccessARN:
    Description: ElasticsearchAccess ARN
    Type: String
  ElasticsearchDomainARN:
    Description: Elasticsearch domain ARN
    Type: String
  CuratedBucketARN:
    Description: Curated bucket ARN
    Type: String
  CuratedBucketAccessARN:
    Description: CuratedBucketAccess ARN
    Type: String
  RedshiftConnectionURL:
    Description: Redshift connection URL
    Type: String
  RedshiftPassword:
    Description: Redshift password.
    NoEcho: 'true'
    Type: String
  RedshiftUsername:
    Description: Redshift username.
    Type: String
  SubmissionsBucketARN:
    Description: Submissions bucket ARN
    Type: String
  SubmissionsBucketAccessARN:
    Description: SubmissionsBucketAccess ARN
    Type: String
Resources:
  CleanOrdersStream:
    Properties:
      RedshiftDestinationConfiguration:
        ClusterJDBCURL: !Ref 'RedshiftConnectionURL'
        CopyCommand:
          CopyOptions: json 'auto'
          DataTableName: orders
        Password: !Ref 'RedshiftPassword'
        RoleARN: !Ref 'CuratedBucketAccessARN'
        S3Configuration:
          BucketARN: !Ref 'CuratedBucketARN'
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: 60
          CompressionFormat: UNCOMPRESSED
          Prefix: orders_stream/
          RoleARN: !Ref 'CuratedBucketAccessARN'
        Username: !Ref 'RedshiftUsername'
    Type: AWS::KinesisFirehose::DeliveryStream
  OrdersStream:
    Properties:
      S3DestinationConfiguration:
        BucketARN: !Ref 'SubmissionsBucketARN'
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 60
        CompressionFormat: UNCOMPRESSED
        Prefix: orders_stream/
        RoleARN: !Ref 'SubmissionsBucketAccessARN'
    Type: AWS::KinesisFirehose::DeliveryStream
  RevenueByStateStream:
    Properties:
      ElasticsearchDestinationConfiguration:
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 50
        DomainARN: !Ref 'ElasticsearchDomainARN'
        IndexName: revenue_by_state
        IndexRotationPeriod: NoRotation
        RetryOptions:
          DurationInSeconds: '60'
        RoleARN: !Ref 'ElasticsearchAccessARN'
        S3BackupMode: AllDocuments
        S3Configuration:
          BucketARN: !Ref 'CuratedBucketARN'
          BufferingHints:
            IntervalInSeconds: '60'
            SizeInMBs: '50'
          CompressionFormat: UNCOMPRESSED
          Prefix: orders_results/revenueByState
          RoleARN: !Ref 'CuratedBucketAccessARN'
        TypeName: RevenueByStateStream
    Type: AWS::KinesisFirehose::DeliveryStream
  TopSKUStream:
    Properties:
      ElasticsearchDestinationConfiguration:
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 50
        DomainARN: !Ref 'ElasticsearchDomainARN'
        IndexName: top_sku
        IndexRotationPeriod: NoRotation
        RetryOptions:
          DurationInSeconds: '60'
        RoleARN: !Ref 'ElasticsearchAccessARN'
        S3BackupMode: AllDocuments
        S3Configuration:
          BucketARN: !Ref 'CuratedBucketARN'
          BufferingHints:
            IntervalInSeconds: '60'
            SizeInMBs: '50'
          CompressionFormat: UNCOMPRESSED
          Prefix: orders_results/topSKU
          RoleARN: !Ref 'CuratedBucketAccessARN'
        TypeName: TopSKU
    Type: AWS::KinesisFirehose::DeliveryStream
Outputs:
  OrdersStreamName:
    Description: Kinesis orders stream name
    Value: !Ref 'OrdersStream'
  OrdersStreamARN:
    Description: Kinesis orders stream ARN
    Value: !Join
      - ':'
      - - arn:aws:firehose
        - !Ref 'AWS::Region'
        - !Ref 'AWS::AccountId'
        - !Join
          - ''
          - - deliverystream/
            - !Ref 'OrdersStream'
  CleanOrdersStreamARN:
    Description: Kinesis clean orders stream ARN
    Value: !Join
      - ':'
      - - arn:aws:firehose
        - !Ref 'AWS::Region'
        - !Ref 'AWS::AccountId'
        - !Join
          - ''
          - - deliverystream/
            - !Ref 'CleanOrdersStream'
  RevenueByStateStreamARN:
    Description: Kinesis revenue by state stream ARN
    Value: !Join
      - ':'
      - - arn:aws:firehose
        - !Ref 'AWS::Region'
        - !Ref 'AWS::AccountId'
        - !Join
          - ''
          - - deliverystream/
            - !Ref 'RevenueByStateStream'
  TopSKUStreamARN:
    Description: Kinesis SKU stream ARN
    Value: !Join
      - ':'
      - - arn:aws:firehose
        - !Ref 'AWS::Region'
        - !Ref 'AWS::AccountId'
        - !Join
          - ''
          - - deliverystream/
            - !Ref 'TopSKUStream'
