AWSTemplateFormatVersion: 2010-09-09
Description: Create the bucket for the Data Lake that contains all the scripts.
Resources:
  s3unitdatalakescriptsprod01:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: unit-data-lake-scripts-prod-01
      VersioningConfiguration:
        Status: Suspended
Outputs:
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [s3unitdatalakescriptsprod01, DomainName]]]
    Description: Name of S3 bucket to hold the data lake data files.
