AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation Template which creates all data lake IAM managed policies and assign it to a IAM group.'
Resources: 
  DataLakeAllZonesReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for read access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/'.
      ManagedPolicyName: DataLakeAllZonesReadPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/*'
      Groups: ['DataLakeAdminGroup','DataLakeDeveloperGroup']
  DataLakeAllZonesWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for write access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/'.
      ManagedPolicyName: DataLakeAllZonesWritePolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/*'
      Groups: ['DataLakeAdminGroup','DataLakeDeveloperGroup']
  DataLakeBZoneReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for read access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/B-Raw-Data-Zone/'.
      ManagedPolicyName: DataLakeBZoneReadPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/B-Raw-Data-Zone/*'
      Groups: ['DataLakeScientistGroup']
  DataLakeCZoneReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for read access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/C-User-Drop-Zone/'.
      ManagedPolicyName: DataLakeCZoneReadPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/C-User-Drop-Zone/*'
      Groups: ['DataLakeScientistGroup']
  DataLakeCZoneWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for write access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/C-User-Drop-Zone/'.
      ManagedPolicyName: DataLakeCZoneWritePolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/C-User-Drop-Zone/*'
      Groups: ['DataLakeScientistGroup']
  DataLakeDZoneCoreReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for read access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/D-Curated-Data-Zone/Core/'.
      ManagedPolicyName: DataLakeDZoneCoreReadPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/D-Curated-Data-Zone/Core/*'
      Groups: ['DataLakeScientistGroup','DataLakeAnalystGroup']
  DataLakeDZoneMartReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for read access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/D-Curated-Data-Zone/Mart/'.
      ManagedPolicyName: DataLakeDZoneMartReadPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/D-Curated-Data-Zone/Mart/*'
      Groups: ['DataLakeScientistGroup','DataLakeAnalystGroup']
  DataLakeEZonePolicyRead:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for read access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/E-Sandbox-Zone/'.
      ManagedPolicyName: DataLakeEZonePolicyRead
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/E-Sandbox-Zone/*'
      Groups: ['DataLakeScientistGroup','DataLakeAnalystGroup']
  DataLakeEZonePolicyWrite:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for write access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/E-Sandbox-Zone/'.
      ManagedPolicyName: DataLakeEZonePolicyWrite
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/E-Sandbox-Zone/*'
      Groups: ['DataLakeScientistGroup','DataLakeAnalystGroup']
  DataLakeFZonePolicyRead:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for read access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/F-Log-Zone/'.
      ManagedPolicyName: DataLakeFZonePolicyRead
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/F-Log-Zone/*'
      Groups: ['DataLakeScientistGroup','DataLakeAnalystGroup']
  DataLakeGZonePolicyRead:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for read access to the data lake bucket 'unit-data-lake-zones-prod-01' with the bucket folder '/G-Archive-Data-Zone/'.
      ManagedPolicyName: DataLakeGZonePolicyRead
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/G-Archive-Data-Zone/*'
      Groups: ['DataLakeScientistGroup','DataLakeAnalystGroup']
  DataLakeAllScriptsPolicyRW:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for read/write access to the data lake bucket 'unit-data-lake-scripts-prod-01' with the bucket folder '/'.
      ManagedPolicyName: DataLakeAllScriptsPolicyRW
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01/*'
      Groups: ['DataLakeAdminGroup','DataLakeDeveloperGroup']
