AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'It creates a single user that is a member of a data lake group. The groups each have
  different IAM policies associated with them. Note: This example also creates an
  AWSAccessKeyId/AWSSecretKey pair associated with the new user.'
Parameters:
  GroupName:
    Type: String
    Default: DataLakeAnalystGroup
    Description: A data lake group
    AllowedValues:
      - DataLakeAdminGroup
      - DataLakeDeveloperGroup
      - DataLakeScientistGroup
      - DataLakeAnalystGroup
      - DataLakeExecutivGroup
      - DownstreamSystemGroup
  Password:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: "^[^\"@]+$"
    ConstraintDescription: The password must be between 8 and 41 characters and can be any printable ASCII character except '/', '"', or '@'
  UserName:
    NoEcho: 'false'
    Type: String
    Description: New account name (firstname.lastname)
    AllowedPattern: "^[a-z0-9:.-]*$"
    ConstraintDescription: Must be a valid user name ^[a-z0-9:.-]*$
Resources:
  DataLakeUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref 'UserName'
      LoginProfile:
        Password: !Ref 'Password'
  DataLakeGroups:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'GroupName'
      Users: [!Ref 'DataLakeUser']
  DataLakeKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'DataLakeUser'
Outputs:
  AccessKey:
    Value: !Ref 'DataLakeKeys'
    Description: AWSAccessKeyId of new user
  SecretKey:
    UserName   : !GetAtt [UserName]
    GroupName  : !GetAtt [GroupName]
    Value      : !GetAtt [DataLakeKeys, SecretAccessKey]
    Description: AWSSecretKey of new data lake user
