AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation Template which creates all data lake IAM managed policies and assign it to a IAM group.'
Resources:
  DataLakeAllZonesReadPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DataLakeAllZonesReadPolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/*'
      Groups: ['DataLakeAdminGroup']
