AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation Template which creates all data lake IAM managed policies and assign it to a IAM group.'
Resources: 
  DataLakeAllZonesReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeAllZonesReadPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/*'
      Groups: []
  DataLakeAllZonesWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeAllZonesWritePolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/*'
      Groups: []
  DataLakeBZoneReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeBZoneReadPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/B-Raw-Data-Zone/*'
      Groups: ['DataLakeAdminGroup','DataLakeDeveloperGroup']
  DataLakeCZoneReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeCZoneReadPolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/C-User-Drop-Zone/*'
      Groups: []
  DataLakeCZoneWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeCZoneWritePolicy
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/C-User-Drop-Zone/*'
      Groups: ['DataLakeScientistGroup']
  DataLakeDZonePolicyCoreRead:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeDZonePolicyCoreRead
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/D-Curated-Data-Zone/Core/*'
      Groups: []
  DataLakeDZonePolicyMartRead:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeDZonePolicyMartRead
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/D-Curated-Data-Zone/Mart/*'
      Groups: []
  DataLakeEZonePolicyRead:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeEZonePolicyRead
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/E-Sandbox-Zone/*'
      Groups: []
  DataLakeEZonePolicyWrite:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeEZonePolicyWrite
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/E-Sandbox-Zone/*'
      Groups: []
  DataLakeFZonePolicyRead:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeFZonePolicyRead
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/F-Log-Zone/*'
      Groups: []
  DataLakeGZonePolicyRead:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeGZonePolicyRead
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-zones-prod-01/G-Archive-Data-Zone/*'
      Groups: ['DataLakeScientistGroup','DataLakeAnalystGroup']
  DataLakeAllScriptsPolicyRW:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeAllScriptsPolicyRW
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01/*'
      Groups: []
  DataLakeJupyterScriptsPolicyRW:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeJupyterScriptsPolicyRW
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01/jupyter/*'
      Groups: []
  DataLakeZeppelinScriptsPolicyRW:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeZeppelinScriptsPolicyRW
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01/zeppelin/*'
      Groups: []
  DataLakeRStudioScriptsPolicyRW:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeRStudioScriptsPolicyRW
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01/rsstudio/*'
      Groups: []
  DataLakeSagemakerScriptsPolicyRW:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DataLakeSagemakerScriptsPolicyRW
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ['s3:GetBucketLocation', 's3:ListAllMyBuckets']
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action: ['s3:ListBucket']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01'
        - Effect: Allow
          Action: ['s3:PutObject','s3:GetObject','s3:DeleteObject']
          Resource: 'arn:aws:s3:::unit-data-lake-scripts-prod-01/sagemaker/*'
      Groups: ['DataLakeScientistGroup']
